services:
  trainer:
    image: ramal/prostate-lesion-segmentation:cu128
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        TORCH_VERSION: "2.7.0"
        TORCHVISION_VERSION: "0.22.0"
        TORCHAUDIO_VERSION: "2.7.0"
        TORCH_INDEX_URL: "https://download.pytorch.org/whl/cu128"
    container_name: thesis-trainer
    working_dir: /workspace
    shm_size: "16gb"
    stdin_open: true
    tty: true
    volumes:
      - ./:/workspace
      - ./outputs:/outputs
      - ./cache:/cache
      - ./data:/data
    environment:
      PYTHONUNBUFFERED: "1"
      TORCH_HOME: /cache/torch
      HF_HOME: /cache/huggingface
      TRANSFORMERS_CACHE: /cache/huggingface/transformers
      PYTHONPATH: /workspace
      BRANCH: main
    ports:
      - "6006:6006"
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
